# Generated by Django 3.2.6 on 2021-09-01 15:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=40)),
                ('column_separator', models.CharField(choices=[(',', 'Comma (,)'), ('.', 'Dot (.)'), ('~', 'Tilda (~)'), (':', 'Colon (:)'), (';', 'Semi colon (:)')], default=',', max_length=2)),
                ('string_character', models.CharField(choices=[('"', 'Double quote (")'), ("'", "Single quote (')")], default='"', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('PROCESSING', 'Processing')], default='PROCESSING', max_length=40)),
                ('result', models.JSONField(default={})),
                ('schema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fakecsv.schema')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[('FULL_NAME', 'Full name'), ('JOB', 'Job'), ('EMAIL', 'Email'), ('DOMAIN_NAME', 'Domain name'), ('PHONE_NUMBER', 'Phone number'), ('COMPANY_NAME', 'Company name'), ('TEXT', 'Text'), ('INTEGER', 'Integer'), ('ADDRESS', 'Address'), ('Date', 'Date')], default='FULL_NAME', max_length=40)),
                ('extra_data', models.JSONField(default={'end_range': 100, 'start_range': 0})),
                ('order', models.IntegerField(help_text='Order by ASC')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fakecsv.schema')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
