# Generated by Django 3.2.6 on 2021-09-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakecsv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='dataset',
            name='rows',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
