# Generated by Django 3.2.6 on 2021-09-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakecsv', '0004_remove_dataset_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='type',
            field=models.CharField(choices=[('FULL_NAME', 'Full name'), ('JOB', 'Job'), ('EMAIL', 'Email'), ('DOMAIN_NAME', 'Domain name'), ('PHONE_NUMBER', 'Phone number'), ('COMPANY_NAME', 'Company name'), ('TEXT', 'Text'), ('INTEGER', 'Integer'), ('ADDRESS', 'Address')], default='FULL_NAME', max_length=40),
        ),
    ]
